######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 31 22:29:20 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += YAML.h
SOURCES += main.cpp
QMAKE_CXXFLAGS+=-std=c++11
